name: Overlay Update
on:
  workflow_call:
    inputs:
      overlay:
        type: string
        required: true
      service:
        type: string
        required: true
      ref:
        type: string
        required: false
    secrets:
      GH_PAT: # Used to merge PRs automatically and triggler workflows (PAT Permissions: Contents - RW | Metadata - RO | Pull requests - RW)
        required: false
env:
  OVERLAY: ${{ inputs.overlay }}
  SERVICE: ${{ inputs.service }}
  SERVICE_REPOSITORY_PATH: service-repository # @TODO: Read from environment
  SERVICE_REPOSITORY_OWNER: silviu-dinu       # @TODO: Read from environment
  REGISTRY_BASE_URL: ghcr.io/silviu-dinu      # @TODO: Read from environment
  GH_TOKEN: ${{ github.token }}
  GH_PAT: ${{ secrets.GH_PAT }} # Used to merge PRs automatically and triggler workflows
jobs:
  Update:
    runs-on: ubuntu-latest
    environment: ${{ inputs.overlay }}
    steps:
    - name: Checkout GitOps repository
      uses: actions/checkout@v4
    - name: Checkout application repository
      uses: actions/checkout@v4
      with:
        path: ${{env.SERVICE_REPOSITORY_PATH}} # See https://github.com/actions/checkout#checkout-multiple-repos-nested
        repository: ${{env.SERVICE_REPOSITORY_OWNER}}/${{ inputs.service }}
        ref: ${{ inputs.ref }}
    - name: Update overlay image
      run: .github/workflows/workflow-steps.sh update-overlay-image
    - name: Create overlay pull request
      run: .github/workflows/workflow-steps.sh create-overlay-pull-request
    - if: inputs.overlay == 'dev'
      name: Auto-merge overlay pull request
      run: .github/workflows/workflow-steps.sh auto-merge-overlay-pull-request
